# Generated by Django 2.1.1 on 2018-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeureul_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='activated_account',
            field=models.BooleanField(default=False),
        ),
    ]
