# Generated by Django 2.1.1 on 2018-09-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeureul_api', '0002_userinfo_activated_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
