# Generated by Django 2.1.1 on 2018-09-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yeureul.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yeureul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('P', 'PASSWORD'), ('A', 'ACTIVATION')], max_length=1)),
                ('key_expires', models.DateTimeField(default=yeureul.models.one_day_hence)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=yeureul.models.get_file_path),
        ),
    ]
