# Generated by Django 2.1.1 on 2018-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeureul', '0002_auto_20180919_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
