# Generated by Django 2.1.4 on 2019-04-29 22:32

import ads.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=30, validators=[django.core.validators.MinValueValidator(500)])),
                ('condition', models.CharField(blank=True, choices=[('N', 'Nouvelle'), ('U', 'Utilisée')], max_length=1)),
                ('description', models.TextField(max_length=2000)),
                ('random_url', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('views_number', models.IntegerField(default=0)),
                ('signal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(default=ads.models.two_days_hence, verbose_name='end date')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='ads.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='AdFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to=ads.models.get_file_path)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='ads.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='AdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('frequency', models.CharField(choices=[('D', 'DAY'), ('W', 'WEEK'), ('M', 'MONTH')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('icon', models.CharField(blank=True, max_length=70, null=True)),
                ('icon_ads', models.CharField(blank=True, max_length=70, null=True)),
                ('widget', models.CharField(blank=True, max_length=20, null=True)),
                ('category_type', models.CharField(blank=True, choices=[('T', 'TOP'), ('B', 'BOTTOM')], default='T', max_length=10, null=True)),
                ('sup_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='ads.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categ_alerts', to='ads.Category'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.AdUser'),
        ),
        migrations.AddField(
            model_name='ad',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loc_ads', to='ads.Location'),
        ),
        migrations.AddField(
            model_name='ad',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcateg_ads', to='ads.Category'),
        ),
    ]
