# Generated by Django 2.1.1 on 2018-09-18 21:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=30, validators=[django.core.validators.MinValueValidator(500)])),
                ('condition', models.CharField(blank=True, choices=[('N', 'New'), ('U', 'Used')], max_length=1)),
                ('description', models.TextField(max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='AdFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='ads_files/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ads.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='AdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('icon', models.CharField(blank=True, max_length=250, null=True)),
                ('sup_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='ads.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.AdUser'),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loc_ads', to='ads.Location'),
        ),
        migrations.AddField(
            model_name='ad',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcateg_ads', to='ads.Category'),
        ),
    ]
