# Generated by Django 2.1.1 on 2018-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
