# Generated by Django 2.1.4 on 2019-04-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='on_pause',
            field=models.BooleanField(default=False),
        ),
    ]
