# Generated by Django 2.1.1 on 2018-09-19 15:22

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='media',
            field=models.FileField(upload_to=ads.models.get_file_path),
        ),
    ]
