# Generated by Django 2.1.1 on 2018-09-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180919_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sup_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='ads.Category'),
        ),
    ]
