# Generated by Django 2.1.1 on 2018-09-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20180910_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='owner',
        ),
    ]
