# Generated by Django 2.1.1 on 2018-09-22 17:22

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='media',
            field=models.ImageField(upload_to=ads.models.get_file_path),
        ),
    ]
