# Generated by Django 2.1.1 on 2018-09-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20180916_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aduser',
            old_name='name',
            new_name='given_name',
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
