# Generated by Django 2.1.1 on 2018-09-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20180922_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='ads.Ad'),
        ),
    ]
