# Generated by Django 2.1.1 on 2018-09-17 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20180916_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='sup_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='ads.Category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(max_length=30, validators=[django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcateg_ads', to='ads.Category'),
        ),
        migrations.AlterField(
            model_name='adfile',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='ads.Category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
