# Generated by Django 2.1.1 on 2018-09-18 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20180917_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='media',
            field=models.FileField(upload_to='ads_media/'),
        ),
        migrations.AlterField(
            model_name='aduser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to=settings.AUTH_USER_MODEL),
        ),
    ]
