# Generated by Django 2.1.1 on 2018-09-24 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20180923_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
