# Generated by Django 2.1.1 on 2018-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ad_random_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
