# Generated by Django 2.1.1 on 2018-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='widget',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
