# Generated by Django 2.1.1 on 2018-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20181206_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('T', 'Nouvelle'), ('B', 'Utilisée')], default='T', max_length=10, null=True),
        ),
    ]
