# Generated by Django 2.1.1 on 2018-12-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_auto_20181215_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'Nouvelle'), ('U', 'Utilisée')], max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('T', 'TOP'), ('B', 'BOTTOM')], default='T', max_length=10, null=True),
        ),
    ]
