# Generated by Django 2.1.4 on 2019-02-24 17:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0017_auto_20190212_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 2, 26, 17, 19, 9, 138077, tzinfo=utc), verbose_name='end date')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='ads.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAdFeatured',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, editable=False, verbose_name='start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 2, 26, 17, 19, 9, 138077, tzinfo=utc), verbose_name='end date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ads.Ad')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ad featured',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
