# Generated by Django 2.1.4 on 2019-02-24 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_adfeatured_historicaladfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_ads',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='icon_ads',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 17, 26, 58, 221714, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 17, 26, 58, 221714, tzinfo=utc), verbose_name='end date'),
        ),
    ]
