# Generated by Django 2.1.4 on 2019-02-26 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_auto_20190224_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(unique=True)),
                ('unfeatured_day', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
            ],
        ),
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 17, 16, 46, 702355, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 17, 16, 46, 702355, tzinfo=utc), verbose_name='end date'),
        ),
    ]
