# Generated by Django 2.1.4 on 2019-02-26 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_auto_20190226_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 44, 46, 720103, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 44, 46, 720103, tzinfo=utc), verbose_name='end date'),
        ),
    ]
