# Generated by Django 2.1.4 on 2019-02-28 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_auto_20190226_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 2, 15, 9, 528728, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicalad',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 2, 15, 9, 528728, tzinfo=utc), verbose_name='end date'),
        ),
    ]
