# Generated by Django 2.1.4 on 2019-02-28 02:30

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_auto_20190228_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfeatured',
            name='unfeatured_day',
        ),
        migrations.AddField(
            model_name='historicalfeatured',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 2, 30, 10, 802748, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 2, 30, 10, 802748, tzinfo=utc), verbose_name='end date'),
        ),
    ]
