# Generated by Django 2.1.4 on 2019-03-01 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_auto_20190228_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creation_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 21, 54, 27, 223492, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicalad',
            name='creation_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 21, 54, 27, 223492, tzinfo=utc), verbose_name='end date'),
        ),
    ]
