# Generated by Django 2.1.4 on 2019-03-01 22:32

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_auto_20190301_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfeatured',
            name='end_date',
            field=models.DateTimeField(default=ads.models.two_days_hence, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicaladfeatured',
            name='end_date',
            field=models.DateTimeField(default=ads.models.two_days_hence, verbose_name='end date'),
        ),
    ]
