# Generated by Django 2.1.4 on 2019-03-05 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_auto_20190301_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
