# Generated by Django 2.1.4 on 2019-03-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_auto_20190309_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
