# Generated by Django 2.1.4 on 2019-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_auto_20190309_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalad',
            name='signal',
            field=models.IntegerField(default=0),
        ),
    ]
