# Generated by Django 2.1.4 on 2019-04-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0036_auto_20190413_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='historicalad',
            name='signal',
        ),
    ]
